title:              Blog 
email:              bilgi@eekinci.com
description:        Not Defterim
author:             eekinci.com
baseurl:            "/clean"
url:                "http://eekinci.com"

# Social Profiles
twitter_username:   emrex
github_username:    webtasarim70
facebook_username:  eekincicom
linkedin_username:  eekincicom

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
